// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfREys7oGKG8hWnMsznUtnziECqIYS5Lw',
    appId: '1:112768177143:web:a2edff3dd44b3966ded4f2',
    messagingSenderId: '112768177143',
    projectId: 'ecommerceapp-2e2fb',
    authDomain: 'ecommerceapp-2e2fb.firebaseapp.com',
    storageBucket: 'ecommerceapp-2e2fb.appspot.com',
    measurementId: 'G-ZRTBPN8GDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXKdmOjKXSJw3OBM0j2IX1bzSFxCmQayM',
    appId: '1:112768177143:android:e122847fb54fdb21ded4f2',
    messagingSenderId: '112768177143',
    projectId: 'ecommerceapp-2e2fb',
    storageBucket: 'ecommerceapp-2e2fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWKjIHSyLGnKTTurGKskYKbQ4gdtQOkI0',
    appId: '1:112768177143:ios:4075361747ff7a38ded4f2',
    messagingSenderId: '112768177143',
    projectId: 'ecommerceapp-2e2fb',
    storageBucket: 'ecommerceapp-2e2fb.appspot.com',
    androidClientId: '112768177143-97j4ih0fcg05jlam7n253u168ftctfh5.apps.googleusercontent.com',
    iosClientId: '112768177143-hod1kfcnv50pkd5886hht6av8ud0ofal.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
